# Generated by Django 3.0.3 on 2020-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200603_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
